import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, JetBrains_Mono, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: ["300", "400", "600"] });
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "600"],
});
const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "600"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SQL Saga",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased bg-black bg-[radial-gradient(circle_at_center,rgba(220,38,38,0.3),rgba(0,0,0,0.9))]`}
      >
        {children}
      </body>
    </html>
  );
}
