import { LanguageSupport, StreamLanguage } from "@codemirror/language";

export const oracleSQL = StreamLanguage.define({
  token: function (stream, state) {
    if (stream.eatSpace()) return null;

    // ✅ Full list of Oracle SQL Keywords
    const keywords = [
      "SELECT",
      "INSERT",
      "UPDATE",
      "DELETE",
      "MERGE",
      "REPLACE",
      "CREATE",
      "ALTER",
      "DROP",
      "TRUNCATE",
      "COMMENT",
      "RENAME",
      "GRANT",
      "REVOKE",
      "ANALYZE",
      "AUDIT",
      "NOAUDIT",
      "EXPLAIN",
      "LOCK",
      "PURGE",
      "FLASHBACK",
      "COMMIT",
      "ROLLBACK",
      "SAVEPOINT",
      "SET",
      "SHOW",
      "CONNECT",
      "DISCONNECT",
      "SESSION",
      "TRANSACTION",
      "TABLE",
      "VIEW",
      "INDEX",
      "SEQUENCE",
      "SYNONYM",
      "DATABASE",
      "SCHEMA",
      "USER",
      "ROLE",
      "CLUSTER",
      "PARTITION",
      "TABLESPACE",
      "MATERIALIZED",
      "LOG",
      "DATAFILE",
      "CASCADE",
      "CONSTRAINT",
      "FOREIGN",
      "PRIMARY",
      "REFERENCES",
      "CHECK",
      "DEFAULT",
      "UNIQUE",
      "NULL",
      "NOT",
      "IDENTITY",
      "JOIN",
      "INNER",
      "LEFT",
      "RIGHT",
      "FULL",
      "OUTER",
      "CROSS",
      "ON",
      "USING",
      "GROUP",
      "HAVING",
      "ORDER",
      "DISTINCT",
      "ALL",
      "IN",
      "EXISTS",
      "BETWEEN",
      "LIKE",
      "AND",
      "OR",
      "CASE",
      "WHEN",
      "THEN",
      "ELSE",
      "END",
      "DECODE",
      "START",
      "WITH",
      "CONNECT",
      "BY",
      "LEVEL",
      "UNION",
      "INTERSECT",
      "MINUS",
    ];

    // ✅ Full list of Oracle SQL Data Types
    const dataTypes = [
      "VARCHAR2",
      "NVARCHAR2",
      "CHAR",
      "NCHAR",
      "CLOB",
      "NCLOB",
      "BLOB",
      "BFILE",
      "RAW",
      "LONG",
      "NUMBER",
      "DECIMAL",
      "INTEGER",
      "FLOAT",
      "REAL",
      "DOUBLE PRECISION",
      "DATE",
      "TIMESTAMP",
      "TIMESTAMP WITH TIME ZONE",
      "TIMESTAMP WITH LOCAL TIME ZONE",
      "INTERVAL YEAR TO MONTH",
      "INTERVAL DAY TO SECOND",
      "BOOLEAN",
      "ROWID",
      "UROWID",
    ];

    // ✅ Full list of Oracle SQL Built-in Functions
    const functions = [
      // String Functions
      "LENGTH",
      "SUBSTR",
      "INSTR",
      "RPAD",
      "LPAD",
      "TRIM",
      "UPPER",
      "LOWER",
      "INITCAP",
      "CONCAT",
      "REPLACE",
      // Numeric Functions
      "ABS",
      "CEIL",
      "FLOOR",
      "MOD",
      "ROUND",
      "TRUNC",
      "SIGN",
      "POWER",
      "SQRT",
      "EXP",
      "LN",
      "LOG",
      "SIN",
      "COS",
      "TAN",
      "ASIN",
      "ACOS",
      "ATAN",
      // Date Functions
      "SYSDATE",
      "SYSTIMESTAMP",
      "CURRENT_DATE",
      "CURRENT_TIMESTAMP",
      "ADD_MONTHS",
      "LAST_DAY",
      "NEXT_DAY",
      "EXTRACT",
      "TO_DATE",
      "TO_CHAR",
      "TO_TIMESTAMP",
      // Aggregate Functions
      "SUM",
      "AVG",
      "MIN",
      "MAX",
      "COUNT",
      // Conditional Functions
      "NVL",
      "NVL2",
      "NULLIF",
      "COALESCE",
      "DECODE",
      // Analytical Functions
      "ROW_NUMBER",
      "RANK",
      "DENSE_RANK",
      "LEAD",
      "LAG",
      "FIRST_VALUE",
      "LAST_VALUE",
      "NTILE",
      // Conversion Functions
      "TO_NUMBER",
      "TO_CHAR",
      "TO_DATE",
      "TO_TIMESTAMP",
      "CAST",
      "CONVERT",
      // Miscellaneous Functions
      "USER",
      "SESSION_USER",
      "SYS_CONTEXT",
      "DBTIMEZONE",
      "SESSIONTIMEZONE",
    ];

    // Identify tokens
    let word = "";
    while (stream.match(/\w+/)) word += stream.current().toUpperCase();

    if (keywords.includes(word)) return "keyword";
    if (dataTypes.includes(word)) return "type";
    if (functions.includes(word)) return "builtin";
    if (word.match(/^'.*'$/)) return "string";

    stream.next();
    return null;
  },
});

export function oracleSQLSupport() {
  return new LanguageSupport(oracleSQL);
}
